CREATE TABLE IF NOT EXISTS schema_migrations (
  id INT PRIMARY KEY AUTO_INCREMENT,
  version VARCHAR(255) NOT NULL UNIQUE,
  executed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
